export const folderColorOptions = [
  {
    name: "blue",
    label: "Niebieski",
    value: "#3B82F6",
    bg: "bg-blue-50",
    text: "text-blue-700",
    dot: "bg-blue-500",
  },
  {
    name: "amber",
    label: "Bursztynowy",
    value: "#F59E0B",
    bg: "bg-amber-50",
    text: "text-amber-700",
    dot: "bg-amber-500",
  },
  {
    name: "emerald",
    label: "Zielony",
    value: "#10B981",
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    dot: "bg-emerald-500",
  },
  {
    name: "violet",
    label: "Fioletowy",
    value: "#8B5CF6",
    bg: "bg-violet-50",
    text: "text-violet-700",
    dot: "bg-violet-500",
  },
  {
    name: "rose",
    label: "Różowy",
    value: "#F43F5E",
    bg: "bg-rose-50",
    text: "text-rose-700",
    dot: "bg-rose-500",
  },
  {
    name: "sky",
    label: "Błękitny",
    value: "#0EA5E9",
    bg: "bg-sky-50",
    text: "text-sky-700",
    dot: "bg-sky-500",
  },
] as const;
